package cli

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/fatih/color"
	"github.com/k15z/axiom/internal/config"
	"github.com/k15z/axiom/internal/provider"
	"github.com/k15z/axiom/internal/scaffold"
	"github.com/mattn/go-isatty"
	"github.com/spf13/cobra"
)

func newAddCmd() *cobra.Command {
	var model string
	var file string

	cmd := &cobra.Command{
		Use:   "add <intent>",
		Short: "Generate a test from a natural-language description",
		Long: `Interactively generate a single behavioral test from a description.

The LLM explores your codebase and produces a test that captures your intent.
You can review and confirm before it's written to disk.

Examples:
  axiom add "all API routes require authentication"
  axiom add "no package imports from the CLI layer"
  axiom add "database connections are always closed" --file db.yml`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			intent := args[0]

			// Verify .axiom/ exists
			testDir := ".axiom"
			if _, err := os.Stat(testDir); os.IsNotExist(err) {
				return &SetupError{Err: fmt.Errorf("test directory %s not found — run %s first", testDir, color.CyanString("axiom init"))}
			}

			// Load config for model default
			cfg, err := config.Load("")
			if err != nil {
				return &SetupError{Err: err}
			}
			if model == "" {
				model = cfg.Model
			}

			repoRoot, _ := filepath.Abs(".")

			// Progress display
			tty := isatty.IsTerminal(os.Stderr.Fd())
			spin := newSpinner(tty, "exploring codebase…")
			spin.start()

			p := provider.FromConfig(provider.ProviderConfig{
				Provider: cfg.Provider,
				APIKey:   cfg.APIKey,
				BaseURL:  cfg.BaseURL,
			})

			yamlContent, err := scaffold.GenerateTest(
				context.Background(),
				p, model, repoRoot, intent,
				func(msg string) {
					spin.update(msg)
				},
			)
			spin.stop()

			if err != nil {
				return fmt.Errorf("generating test: %w", err)
			}

			// Display the generated test
			fmt.Println()
			gray := color.New(color.FgHiBlack).SprintFunc()
			fmt.Println(gray("Generated test:"))
			fmt.Println()
			fmt.Println(yamlContent)
			fmt.Println()

			// Determine target file
			targetFile := file
			if tty && !cmd.Flags().Changed("file") {
				if chosen, ok := promptFileChoice(testDir); ok {
					targetFile = chosen
				}
			}

			// Interactive confirmation
			targetPath := filepath.Join(testDir, targetFile)
			if !tty {
				// Non-interactive: just write it
				return appendTest(targetPath, yamlContent)
			}

			fmt.Printf("Add this test to %s? [Y/n] ", color.CyanString(targetPath))
			reader := bufio.NewReader(os.Stdin)
			answer, _ := reader.ReadString('\n')
			answer = strings.TrimSpace(strings.ToLower(answer))

			if answer == "" || answer == "y" || answer == "yes" {
				if err := appendTest(targetPath, yamlContent); err != nil {
					return err
				}
				fmt.Printf("Test added to %s\n", color.CyanString(targetPath))
				return nil
			}

			fmt.Println("Discarded.")
			return nil
		},
	}

	cmd.Flags().StringVarP(&model, "model", "m", "", "Override LLM model")
	cmd.Flags().StringVarP(&file, "file", "f", "tests.yml", "Target YAML file inside .axiom/")

	return cmd
}

// promptFileChoice lists YAML files in testDir and asks the user to pick one.
// Returns the chosen filename and true, or ("", false) if there's only one file
// or no files (caller should use the default).
func promptFileChoice(testDir string) (string, bool) {
	entries, err := os.ReadDir(testDir)
	if err != nil {
		return "", false
	}
	var files []string
	for _, e := range entries {
		if e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		if strings.HasSuffix(e.Name(), ".yml") || strings.HasSuffix(e.Name(), ".yaml") {
			files = append(files, e.Name())
		}
	}
	sort.Strings(files)
	if len(files) <= 1 {
		return "", false
	}

	fmt.Println("Multiple test files found:")
	for i, f := range files {
		fmt.Printf("  %d) %s\n", i+1, f)
	}
	fmt.Printf("Choose a file [1-%d]: ", len(files))

	reader := bufio.NewReader(os.Stdin)
	answer, _ := reader.ReadString('\n')
	answer = strings.TrimSpace(answer)

	var idx int
	if _, err := fmt.Sscanf(answer, "%d", &idx); err != nil || idx < 1 || idx > len(files) {
		// Invalid input — use first file
		fmt.Printf("Using %s\n", files[0])
		return files[0], true
	}
	return files[idx-1], true
}

// appendTest appends a test YAML block to a file, creating it if needed.
func appendTest(path, yamlContent string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dir, err)
	}

	if _, err := os.Stat(path); os.IsNotExist(err) {
		// New file: write with header
		header := "# Generated by axiom add\n# See: https://github.com/k15z/axiom\n\n"
		return os.WriteFile(path, []byte(header+yamlContent+"\n"), 0o644)
	}

	// Existing file: append with separator
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return fmt.Errorf("opening %s: %w", path, err)
	}
	defer f.Close()

	_, err = fmt.Fprintf(f, "\n%s\n", yamlContent)
	return err
}
