package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/fatih/color"
	"github.com/k15z/axiom/internal/config"
	"github.com/k15z/axiom/internal/provider"
	"github.com/k15z/axiom/internal/scaffold"
	"github.com/mattn/go-isatty"
	"github.com/spf13/cobra"
)

func newInitCmd() *cobra.Command {
	var (
		model string
		prov  string
	)

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize axiom in the current project",
		Long: `Analyze the codebase and generate behavioral tests.

Requires an API key to be set (in environment or .env file).
The LLM explores your code and generates tests that verify architectural
intent, security invariants, and design constraints.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := ".axiom"

			if _, err := os.Stat(dir); err == nil {
				return &SetupError{Err: fmt.Errorf("%s already exists — remove it first to re-initialize", dir)}
			}

			// Start with defaults, then apply CLI overrides
			cfg := config.Default()
			if model != "" {
				cfg.Model = model
			}
			if prov != "" {
				cfg.Provider = prov
			}

			// Resolve provider and load the correct API key
			if err := cfg.ResolveKey(); err != nil {
				return &SetupError{Err: err}
			}

			repoRoot, _ := filepath.Abs(".")
			p := provider.FromConfig(provider.ProviderConfig{
				Provider: cfg.Provider,
				APIKey:   cfg.APIKey,
				BaseURL:  cfg.BaseURL,
			})

			// Progress display
			tty := isatty.IsTerminal(os.Stderr.Fd())
			spin := newSpinner(tty, "analyzing codebase…")
			spin.start()

			yamlContent, err := scaffold.GenerateTests(
				context.Background(),
				p, cfg.Model, repoRoot,
				func(msg string) {
					spin.update(msg)
				},
			)
			spin.stop()

			if err != nil {
				return fmt.Errorf("generating tests: %w", err)
			}

			// Create .axiom/ and write files
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return fmt.Errorf("creating %s: %w", dir, err)
			}

			testsPath := filepath.Join(dir, "tests.yml")
			header := "# Generated by axiom init\n# See: https://github.com/k15z/axiom\n\n"
			if err := os.WriteFile(testsPath, []byte(header+yamlContent+"\n"), 0o644); err != nil {
				return fmt.Errorf("writing %s: %w", testsPath, err)
			}

			// Write axiom.yml with the model used for init
			sampleCfg := fmt.Sprintf("# axiom configuration\n# See: https://github.com/k15z/axiom\nmodel: %s\n", cfg.Model)
			if err := os.WriteFile("axiom.yml", []byte(sampleCfg), 0o644); err != nil {
				return fmt.Errorf("writing axiom.yml: %w", err)
			}

			// Print summary
			fmt.Println()
			printGeneratedTests(yamlContent)
			fmt.Println()
			fmt.Println("Created axiom.yml with default configuration.")
			fmt.Printf("Run %s to verify your codebase against these tests.\n", color.CyanString("axiom run"))

			return nil
		},
	}

	cmd.Flags().StringVarP(&model, "model", "m", "", "LLM model to use")
	cmd.Flags().StringVarP(&prov, "provider", "p", "", "LLM provider: anthropic, openai, or gemini")

	return cmd
}

// printGeneratedTests parses the YAML loosely to show test names.
func printGeneratedTests(yaml string) {
	var names []string
	for _, line := range strings.Split(yaml, "\n") {
		if strings.HasPrefix(line, "test_") && strings.HasSuffix(strings.TrimSpace(line), ":") {
			name := strings.TrimSuffix(strings.TrimSpace(line), ":")
			names = append(names, name)
		}
	}

	if len(names) == 0 {
		fmt.Printf("Generated tests in %s\n", color.CyanString(".axiom/tests.yml"))
		return
	}

	fmt.Printf("Generated %d tests in %s:\n", len(names), color.CyanString(".axiom/tests.yml"))
	for _, name := range names {
		fmt.Printf("  %s %s\n", color.GreenString("•"), name)
	}
}
