package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/fatih/color"
	"github.com/k15z/axiom/internal/config"
	"github.com/k15z/axiom/internal/scaffold"
	"github.com/mattn/go-isatty"
	"github.com/spf13/cobra"
)

const sampleConfig = `# axiom configuration
# See: https://github.com/k15z/axiom
model: claude-haiku-4-5-20251001
`

func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Initialize axiom in the current project",
		Long: `Analyze the codebase and generate behavioral tests.

Requires ANTHROPIC_API_KEY to be set (in environment or .env file).
The LLM explores your code and generates tests that verify architectural
intent, security invariants, and design constraints.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := ".axiom"

			if _, err := os.Stat(dir); err == nil {
				return fmt.Errorf("%s already exists — remove it first to re-initialize", dir)
			}

			// Load API key
			apiKey, err := config.LoadAPIKey()
			if err != nil {
				return err
			}

			model := "claude-haiku-4-5-20251001"
			repoRoot, _ := filepath.Abs(".")

			// Progress display
			tty := isatty.IsTerminal(os.Stderr.Fd())
			spin := newSpinner(tty, "analyzing codebase…")
			spin.start()

			yamlContent, err := scaffold.GenerateTests(
				context.Background(),
				apiKey, model, repoRoot,
				func(msg string) {
					spin.update(msg)
				},
			)
			spin.stop()

			if err != nil {
				return fmt.Errorf("generating tests: %w", err)
			}

			// Create .axiom/ and write files
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return fmt.Errorf("creating %s: %w", dir, err)
			}

			testsPath := filepath.Join(dir, "tests.yml")
			header := "# Generated by axiom init\n# See: https://github.com/k15z/axiom\n\n"
			if err := os.WriteFile(testsPath, []byte(header+yamlContent+"\n"), 0o644); err != nil {
				return fmt.Errorf("writing %s: %w", testsPath, err)
			}

			if err := os.WriteFile("axiom.yml", []byte(sampleConfig), 0o644); err != nil {
				return fmt.Errorf("writing axiom.yml: %w", err)
			}

			// Print summary
			fmt.Println()
			printGeneratedTests(yamlContent)
			fmt.Println()
			fmt.Println("Created axiom.yml with default configuration.")
			fmt.Printf("Run %s to verify your codebase against these tests.\n", color.CyanString("axiom run"))

			return nil
		},
	}
}

// printGeneratedTests parses the YAML loosely to show test names.
func printGeneratedTests(yaml string) {
	var names []string
	for _, line := range strings.Split(yaml, "\n") {
		if strings.HasPrefix(line, "test_") && strings.HasSuffix(strings.TrimSpace(line), ":") {
			name := strings.TrimSuffix(strings.TrimSpace(line), ":")
			names = append(names, name)
		}
	}

	if len(names) == 0 {
		fmt.Printf("Generated tests in %s\n", color.CyanString(".axiom/tests.yml"))
		return
	}

	fmt.Printf("Generated %d tests in %s:\n", len(names), color.CyanString(".axiom/tests.yml"))
	for _, name := range names {
		fmt.Printf("  %s %s\n", color.GreenString("•"), name)
	}
}

