package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/fatih/color"
	"github.com/k15z/axiom/internal/config"
	"github.com/k15z/axiom/internal/scaffold"
	"github.com/mattn/go-isatty"
	"github.com/spf13/cobra"
)

const sampleConfig = `# axiom configuration
# See: https://github.com/k15z/axiom
model: claude-haiku-4-5-20251001
`

func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Initialize axiom in the current project",
		Long: `Analyze the codebase and generate behavioral tests.

Requires ANTHROPIC_API_KEY to be set (in environment or .env file).
The LLM explores your code and generates tests that verify architectural
intent, security invariants, and design constraints.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := ".axiom"

			if _, err := os.Stat(dir); err == nil {
				return fmt.Errorf("%s already exists — remove it first to re-initialize", dir)
			}

			// Load API key
			apiKey, err := config.LoadAPIKey()
			if err != nil {
				return err
			}

			model := "claude-haiku-4-5-20251001"
			repoRoot, _ := filepath.Abs(".")

			// Progress display
			tty := isatty.IsTerminal(os.Stderr.Fd())
			spinner := newInitSpinner(tty)
			spinner.start()

			yamlContent, err := scaffold.GenerateTests(
				context.Background(),
				apiKey, model, repoRoot,
				func(msg string) {
					spinner.update(msg)
				},
			)
			spinner.stop()

			if err != nil {
				return fmt.Errorf("generating tests: %w", err)
			}

			// Create .axiom/ and write files
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return fmt.Errorf("creating %s: %w", dir, err)
			}

			testsPath := filepath.Join(dir, "tests.yml")
			header := "# Generated by axiom init\n# See: https://github.com/k15z/axiom\n\n"
			if err := os.WriteFile(testsPath, []byte(header+yamlContent+"\n"), 0o644); err != nil {
				return fmt.Errorf("writing %s: %w", testsPath, err)
			}

			if err := os.WriteFile("axiom.yml", []byte(sampleConfig), 0o644); err != nil {
				return fmt.Errorf("writing axiom.yml: %w", err)
			}

			// Print summary
			fmt.Println()
			printGeneratedTests(yamlContent)
			fmt.Println()
			fmt.Println("Created axiom.yml with default configuration.")
			fmt.Printf("Run %s to verify your codebase against these tests.\n", color.CyanString("axiom run"))

			return nil
		},
	}
}

// printGeneratedTests parses the YAML loosely to show test names.
func printGeneratedTests(yaml string) {
	var names []string
	for _, line := range strings.Split(yaml, "\n") {
		if strings.HasPrefix(line, "test_") && strings.HasSuffix(strings.TrimSpace(line), ":") {
			name := strings.TrimSuffix(strings.TrimSpace(line), ":")
			names = append(names, name)
		}
	}

	if len(names) == 0 {
		fmt.Printf("Generated tests in %s\n", color.CyanString(".axiom/tests.yml"))
		return
	}

	fmt.Printf("Generated %d tests in %s:\n", len(names), color.CyanString(".axiom/tests.yml"))
	for _, name := range names {
		fmt.Printf("  %s %s\n", color.GreenString("•"), name)
	}
}

// initSpinner provides a simple single-line spinner for the init process.
type initSpinner struct {
	tty    bool
	mu     sync.Mutex
	status string
	frame  int
	stopCh chan struct{}
	done   chan struct{}
}

var spinnerFrames = []string{"⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"}

func newInitSpinner(tty bool) *initSpinner {
	return &initSpinner{
		tty:    tty,
		status: "analyzing codebase…",
		stopCh: make(chan struct{}),
		done:   make(chan struct{}),
	}
}

func (s *initSpinner) start() {
	if !s.tty {
		fmt.Fprintln(os.Stderr, "Analyzing codebase...")
		go func() {
			defer close(s.done)
			for {
				select {
				case <-s.stopCh:
					return
				}
			}
		}()
		return
	}
	go func() {
		defer close(s.done)
		ticker := time.NewTicker(80 * time.Millisecond)
		defer ticker.Stop()
		for {
			select {
			case <-s.stopCh:
				// Clear the spinner line
				fmt.Fprintf(os.Stderr, "\033[2K\r")
				return
			case <-ticker.C:
				s.mu.Lock()
				frame := spinnerFrames[s.frame%len(spinnerFrames)]
				status := s.status
				s.frame++
				s.mu.Unlock()
				cyan := color.New(color.FgCyan).SprintFunc()
				gray := color.New(color.FgHiBlack).SprintFunc()
				fmt.Fprintf(os.Stderr, "\033[2K\r  %s %s", cyan(frame), gray(status))
			}
		}
	}()
}

func (s *initSpinner) update(msg string) {
	if !s.tty {
		fmt.Fprintf(os.Stderr, "  → %s\n", msg)
		return
	}
	s.mu.Lock()
	s.status = msg
	s.mu.Unlock()
}

func (s *initSpinner) stop() {
	close(s.stopCh)
	<-s.done
}
